# Generated by Django 3.2.3 on 2021-05-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_price', '0003_alter_coin_price_guess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='price_guess',
            field=models.DecimalField(decimal_places=8, max_digits=1000),
        ),
    ]
